# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Kore-web-sdk

on:
  push:
    branches:
      - v2/dev 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@uday_test'
      - name: Installing the dependencies   
        run: npm ci
      - name: Run the UMD build
        run: npm run build-umd
      - name: Run ESM build
        run: npm run build
      - name: Prepare the files for npm publish
        run: node npmPublish.js
      - name: Publish the package
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKENNPM }}


