# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Kore-web-sdk

on:
  push:
    branches:
      - v2/dev 
      - v2/dev-rc1
      - v3/dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: '@koredev'
      - name: Installing the dependencies
        run: npm ci
      - name: Runing build and publish
        run: npm run-script npm-publish-dev-auto -- --commitId=${{github.sha}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKENNPM}}


